[robot]
	type = 'ATRV'
	[[robot.actuators]]
		id = 'motion1'
		type = 'MotionVW'
		[robot.actuators.interface]
			type = 'socket'
	[[robot.actuators]]
		id = 'keyboard'
		type = 'Keyboard'
		[robot.actuators.interface]
			type = 'socket'
		[robot.actuators.properties]
			ControlType = 'Position'
	[[robot.sensors]]
		id = 'pose'
		type = 'Pose'
		[robot.sensors.interface]
			type = 'socket'
	[[robot.sensors]]
		id = 'IR1'
		type = 'Infrared'
		[robot.sensors.interface]
			type = 'socket'
	[[robot.sensors]]
		id = 'IR2'
		type = 'Infrared'
		[robot.sensors.interface]
			type = 'socket'
	[[robot.sensors]]
		id = 'IR3'
		type = 'Infrared'
		[robot.sensors.interface]
			type = 'socket'
	[[robot.sensors]]
		id = 'IR4'
		type = 'Infrared'
		[robot.sensors.interface]
			type = 'socket'
	[[robot.collision]]
		zTran = 0.3
		x = 0.8
		y = 0.6
		z = 0.05
