[game]
	numrobot = 1
	numobject = 2
	map = "tutorial"
	actuators = ["MotionVW", "Keyboard"]
	sensors = ["Pose"]
	[[game.objects]]
		file = "objects"
		name = "GOAL"
		x = 7
		y = 7
		z = 0.01
		[game.objects.properties]
			Label = "GOAL"
			GOAL = true
	[[game.objects]]
		file = "ball"
		name = "BALL"
		x = 1
		y = 1
		z = 1
		[game.objects.properties]
			Label = "BALL"
			Object = true
	[[game.camera_position]]
		x_cam = -18.0
		y_cam = -6.7
		z_cam = 10.8
		p_cam = 1.09
		q_cam = 0
		r_cam = -1.14
	[[game.robot_position]]
		x = 7
		y = 7
	[[game.time]]
		timeSimu = 30
		scoreZero = true
		endTime = false
