# hit the balls to gain points
# instead if the robot hits the wall, it loses points

[game]
	numrobot = 1
	numobject = 3
	map = "tutorial"
	actuators = ["MotionVW", "Keyboard"]
	sensors = ["Pose"]
	[[game.objects]]
		file = "objects"
		name = "GOAL"
		x = 7
		y = 7
		z = 0.01
		[game.objects.properties]
			Label = "GOAL"
			GOAL = true
	[[game.objects]]
		file = "ball"
		name = "BALL1"
		x = 1
		y = 1
		z = 1
		[game.objects.properties]
			Label = "BALL"
			Object = true
	[[game.objects]]
		file = "ball"
		name = "BALL2"
		x = 2
		y = 2
		z = 2
		[game.objects.properties]
			Label = "BALL"
			Object = true
	[[game.camera_position]]
		x_cam = -18.0
		y_cam = -6.7
		z_cam = 10.8
		p_cam = 1.09
		q_cam = 0
		r_cam = -1.14
	[[game.robot_position]]
		x = 7
		y = 7
		z = 0
		p = 0
		q = 0
		r = 0
	[[game.time]]
		timeSimu = 30
		scoreZero = true
		endTime = false
